### ISSUE TITLE
Server crashes when using it.

### ISSUE THREAD

**Issue by LIvesz** [skmedix/HideNames#9]
My friends server crashes it while using it. It is not cauldron. and we have many mods, but nothing to do with clientside or anything along those lines. 

It is 1.12.2 and we don't know what to do.

**Comment by skmedix** [comment]
Forge or SpongeForge? Can you provide the crashlog?

**Comment by LIvesz** [comment]
it is forge, and here is the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 11/29/18 7:24 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from FTB Utilities (ftbutilities)
Caused by: java.lang.NullPointerException
	at com.tlf.HN.commands.CommandName.func_71518_a(CommandName.java:42)
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_71518_a(CommandOverride.java:76)
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.<init>(CommandOverride.java:50)
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.create(CommandOverride.java:36)
	at com.feed_the_beast.ftbutilities.FTBUtilities.onServerStarted(FTBUtilities.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:807)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-862.2.3.el7.x86_64
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 489662264 bytes (466 MB) / 917504000 bytes (875 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms128M -Xmx2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State      | ID              | Version           | Source                                | Signature                                |
	|:---------- |:--------------- |:----------------- |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA  | minecraft       | 1.12.2            | minecraft.jar                         | None                                     |
	| UCHIJAAAA  | mcp             | 9.42              | minecraft.jar                         | None                                     |
	| UCHIJAAAA  | FML             | 8.0.99.99         | minecraft_server.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA  | forge           | 14.23.5.2770      | minecraft_server.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA  | obfuscate       | 0.2.6             | minecraft.jar                         | None                                     |
	| UCHIJAAAA  | srm-hooks       | 1.12.2-1.0.0      | minecraft.jar                         | None                                     |
	| UCHIJAAAA  | securitycraft   | v1.8.10           | [1.12.2] SecurityCraft v1.8.10.jar    | None                                     |
	| UCHIJAAAA  | bbs_mod         | ${version}        | bbs_mod-1.12.2-1.3.202.jar            | None                                     |
	| UCHIJAAAA  | customnpcs      | 1.12              | CustomNPCs_1.12.2(26aug18).jar        | None                                     |
	| UCHIJAAAA  | cdm             | 0.4.1             | device-mod-0.4.1-1.12.2.jar           | None                                     |
	| UCHIJAAAA  | fcl             | 1.XII.44          | Fexcraft Common Library-1.XII.44b.jar | None                                     |
	| UCHIJAAAA  | foodexpansion   | 1.3               | FoodExpansion1.3.3-1.12.2.jar         | None                                     |
	| UCHIJAAAA  | fsmm            | 2.2.3             | FSMM-2.2.3-1.12.x.jar                 | None                                     |
	| UCHIJAAAA  | ftblib          | 5.4.0.65          | FTBLib-5.4.0.65.jar                   | None                                     |
	| UCHIJAAAEE | ftbutilities    | 5.3.0.62          | FTBUtilities-5.3.0.62.jar             | None                                     |
	| UCHIJAAA   | cfm             | 5.17.0            | furniture-5.17.0-1.12.2.jar           | None                                     |
	| UCHIJAAA   | ironman         | Beta-1.12.2-1.2.5 | IronMan-1.12.2-Beta-1.12.2-1.2.5.jar  | None                                     |
	| UCHIJAAA   | speedsterheroes | 1.12.2-2.0.10     | SpeedsterHeroes-1.12.2-2.0.10.jar     | None                                     |
	| UCHIJAAA   | lucraftcore     | 1.12.2-2.3.2      | LucraftCore-1.12.2-2.3.2.jar          | None                                     |
	| UCHIJAAA   | heroesexpansion | 1.12.2-1.2.1      | HeroesExpansion-1.12.2-1.2.1.jar      | None                                     |
	| UCHIJAAA   | hidenames       | 1.4               | HideNames-1.12-1.4.jar                | None                                     |
	| UCHIJAAA   | secretroomsmod  | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar       | None                                     |
	| UCHIJAAA   | vehicle         | 0.31.0            | vehicle-mod-0.31.0-1.12.2.jar         | None                                     |

	Loaded coremods (and transformers): 
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.3.2.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 30; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

we have ftb utilities if that messes with it but idk

**Comment by skmedix** [comment]
I'll try to reproduce that asap, give me max 2 days

**Comment by LIvesz** [comment]
nvm issue is fixed. The problem was ftb. Sorry to waste time ;-;
